RandomCsvRowStep keep on choosing the first row
Hyperfoil/Hyperfoil pull request #278
Opened 2023-03-10 15:52 UTC by franz1981

RandomCsvRowStep.Builder is stucked parsing the same first line again and again.

Added tests to verify different `invoke`s select different lines (and these are correct) and that parsing is correctly loading all lines.

Spotted another bug on parsing that doesn't correctly load quoted values spanning multiple lines

2023-03-13 06:32 UTC, jesperpedersen requested changes

2023-03-13 06:32 UTC, jesperpedersen commented on core/src/main/java/io/hyperfoil/core/generators/RandomCsvRowStep.java
> +   public String[][] rows() {
Can this be package protected instead ?

2023-03-13 06:32 UTC, jesperpedersen commented on core/src/main/java/io/hyperfoil/core/generators/RandomCsvRowStep.java
> +      public Builder customSelector(IntUnaryOperator selector) {
Package protected ?

2023-03-13 08:41 UTC, franz1981 commented
@jesperpedersen thanks for reviewing! added an additional commit to address comments

2023-03-13 08:42 UTC, jesperpedersen commented
Please, squash and force push

2023-03-14 02:57 UTC, jimma commented
Only some minor checkstyle issue : 
```[INFO] Starting audit...
/code/Hyperfoil/core/src/test/java/io/hyperfoil/core/generators/RandomCsvRowStepTest.java:51: 'VARIABLE_DEF' should be separated from previous statement.
Audit done.```

2023-03-14 06:10 UTC, franz1981 commented
@jesperpedersen it seems serialization must be fixed due the changes. I will add a test as well, so please don't merge it yet!

2023-03-14 08:58 UTC, franz1981 commented
@jesperpedersen waiting user approval and this is done :+1:

2023-03-14 09:07 UTC, jesperpedersen commented
checkstyle...

2023-03-14 09:58 UTC, jesperpedersen commented
Still failing -- are you using `mvn clean package` ?

2023-03-14 10:07 UTC, franz1981 commented
@franz1981 yep, just needed last push

2023-03-14 10:08 UTC, franz1981 commented
```
io.hyperfoil.http.steps.HttpRequestTest
```
this is failing but seems unrelated, I can take a look

2023-03-14 10:12 UTC, jesperpedersen commented
Its a transitive failure... but it needs investigation.

2023-03-14 10:13 UTC, franz1981 commented
But is intermittent in the CI, or...always happen?

2023-03-14 10:14 UTC, jesperpedersen commented
Rebased, and merged.

Thanks for your contribution !

2023-03-14 10:14 UTC, closed without merging