Update: README.md
Hyperfoil/Hyperfoil pull request #286
Opened 2023-04-04 03:43 UTC by shivam-sharma7

Update: README.md

2023-04-04 03:44 UTC, shivam-sharma7 commented
review/ @jesperpedersen

2023-04-04 15:14 UTC, jesperpedersen requested changes

2023-04-05 06:19 UTC, shivam-sharma7 commented on README.md
> +Contributions to `Horreum` Please check our [CONTRIBUTING.md](https://github.com/Hyperfoil/Horreum/blob/master/CONTRIBUTING.md)
I thought that we don't need to create another and then I have linked Horreum CONTRIBUTING.md file.

2023-04-05 13:16 UTC, jesperpedersen commented on README.md
> +Contributions to `Horreum` Please check our [CONTRIBUTING.md](https://github.com/Hyperfoil/Horreum/blob/master/CONTRIBUTING.md)
Every project needs to have their own

2023-04-06 12:35 UTC, jesperpedersen requested changes

2023-04-06 12:35 UTC, jesperpedersen commented on README.md
> +Contributions to `Horreum` Please check our [CONTRIBUTING.md](https://github.com/Hyperfoil/Horreum/blob/master/CONTRIBUTING.md)
Nothing has changed - you need to include the file, and update the URL

2023-04-11 16:56 UTC, jesperpedersen requested changes

2023-04-11 16:56 UTC, jesperpedersen commented on README.md
> +Contributions to `Hyperfoil` Please check our [CONTRIBUTING.md](https://github.com/Hyperfoil/Horreum/blob/master/CONTRIBUTING.md)
Replace Horreum

2023-04-15 15:45 UTC, shivam-sharma7 commented on README.md
> +Contributions to `Hyperfoil` Please check our [CONTRIBUTING.md](https://github.com/Hyperfoil/Horreum/blob/master/CONTRIBUTING.md)
Replace already

2023-04-19 13:29 UTC, jesperpedersen requested changes

2023-04-19 13:29 UTC, jesperpedersen commented on README.md
> +Contributions to `Hyperfoil` Please check our [CONTRIBUTING.md](https://github.com/Hyperfoil/Horreum/blob/master/CONTRIBUTING.md)
It is still Horreum - everything needs to be separate

2023-04-28 02:55 UTC, closed without merging